name: 'DataBurst Python Semantic Versioning'
description: 'Automated semantic versioning using custom emoji commit parser'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
  
  dry_run:
    description: 'Perform a dry run without making changes'
    required: false
    default: 'false'

  semantic_release_dir:
    description: 'Directory of the semantic release action'
    required: false
    default: ${{ github.event.repository.name }}
    
  branch:
    description: 'Branch to release from'
    required: false
    default: 'main'
    
  prerelease:
    description: 'Create a prerelease'
    required: false
    default: 'false'
    
  commit_author:
    description: 'Commit author for release commits'
    required: false
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

  semantic_release_config:
    description: 'Semantic release config'
    required: false
    default: 'pyproject.toml'

runs:
  using: 'composite'
  
  steps:
    - name: Checkout ${{ github.event.repository.name }} repository
      uses: actions/checkout@v4 

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"

    - name: Install the project
      shell: bash
      run: uv sync --locked 
        
    - name: Debug
      shell: bash
      run: ls -la ${{ github.workspace }}
