name: 'DataBurst Python Semantic Versioning'
author: 'Mostafa Ghadimi'
description: 'Automated semantic versioning using custom emoji commit parser'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  dry_run:
    description: 'Perform a dry run without making changes'
    required: false
    default: 'false'
    
  branch:
    description: 'Branch to release from'
    required: false
    default: 'main'
    
  prerelease:
    description: 'Create a prerelease'
    required: false
    default: 'false'
    
  prerelease_branch:
    description: 'Branch name for pre-releases (e.g., dev, staging, beta). Only applies when prerelease is true.'
    required: false
    default: 'dev'

  prerelease_token:
    description: 'Token/suffix to append to pre-release versions (e.g., rc, alpha, beta). Only applies when prerelease is true.'
    required: false
    default: 'rc'

  commit_author:
    description: 'Commit author for release commits'
    required: false
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

  semantic_release_config:
    description: 'Semantic release config file name'
    required: false
    default: '/app/python-semantic-release-config.toml'

  debug:
    description: 'Enable debug output'
    required: false
    default: 'false'

  gh_token:
    description: 'GitHub token with write permissions to push releases and tags.'
    required: true

outputs:
  version:
    description: 'The new version number'
  
  released:
    description: 'Whether a new release was created'
    
  tag:
    description: 'The new git tag'

runs:
  using: 'docker'
  image: 'Dockerfile'