name: 'DataBurst Python Semantic Versioning'
author: 'Mostafa Ghadimi'
description: 'Automated semantic versioning using custom emoji commit parser'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
  
  dry_run:
    description: 'Perform a dry run without making changes'
    required: false
    default: 'false'
    
  branch:
    description: 'Branch to release from'
    required: false
    default: 'main'
    
  prerelease:
    description: 'Create a prerelease'
    required: false
    default: 'false'
    
  commit_author:
    description: 'Commit author for release commits'
    required: false
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

  semantic_release_config:
    description: 'Semantic release config file name'
    required: false
    default: 'python-semantic-release-config.toml'

outputs:
  version:
    description: 'The new version number'
  
  released:
    description: 'Whether a new release was created'
    
  tag:
    description: 'The new git tag'

runs:
  using: 'docker'
  image: 'src/python-semantic-versioning/Dockerfile'